name: Prueba de GitHub Actions
run-name: Primer workflow de prueba - PUSH
on: [push]
jobs:
  setup-java:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v3.12.0
        with:
          distribution: oracle
          java-version: 17
          java-package: jdk
  run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile and run Java Code
        run: |
          javac ./src/Main.java
          java ./src/Main.java