name: Trigger-Schedule Test
run-name: Trigger-Schedule Test
on:
  schedule:
    - cron: '0/2 * * * *'
jobs:
  do-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Create Alert - Schedule
        run: echo "Esta es la alerta creada para identificar el SCHEDULE"
