name: Trigger SCHEDULE Test
run-name: Trigger SCHEDULE Test
on:
  schedule:
    - cron: '5 * 11 11 *'
jobs:
  do-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Create Alert - Schedule
        run: echo "Esta es la alerta creada para identificar el SCHEDULE"
