name: Trigger-Schedule Test
run-name: Trigger-Schedule Test
on:
  schedule:
    - cron: '5 * 22 11 WED'
jobs:
  do-alert:
    runs-on: ubuntu-talest
    steps:
      - name: Create Alert
        run: echo "Esta es la alerta creada para identificar el scheduler"
