name: Trigger PULL REQUEST Test
run-name: Trigger PULL REQUEST Test
on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize
  workflow_dispatch:
    inputs:
      alerta:
        description: 'nivel'
        required: true
        default: medio
        type: choice
        options:
          - bajo
          - medio
jobs:
  do-alert-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Create Alert - DISPATCH
        run: echo "Esta es la alerta creada para identificar el DISPATCH"
  do-alert-pr:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Create Alert - PR
        run: echo "Esta es la alerta creada para identificar el PR"

