name: Saludo usando variables
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        env:
          NOMBRE: Johny
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
